In [5]:
#Connect to Google drive
from google.colab import drive

drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [3]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

--2025-05-04 21:29:45--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2025-05-04 21:29:46--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2025-05-04 21:29:46--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [6]:
embeddings_size = 200;

In [7]:
import numpy as np
def load_glove_embeddings(file_path):
    embeddings_index = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.array(values[1:], dtype='float32')
            embeddings_index[word] = vector
    return embeddings_index

glove_path = "/content/drive/MyDrive/574_Project/glove.6B.200d.txt"  # Change to "50d", "200d", or "300d" if needed
embeddings_index = load_glove_embeddings(glove_path)

print(f"Loaded {len(embeddings_index)} word vectors.")

Loaded 400000 word vectors.


In [42]:
word = "ronald"
if word in embeddings_index:
    print(embeddings_index[word])
else:
    print("Word not found in GloVe embeddings.")

[-9.8809e-01  4.3912e-01 -1.5968e-01 -6.4761e-01  4.5850e-01 -3.8629e-01
  3.1324e-01 -1.4723e-01  6.0489e-01  3.4617e-01 -1.7198e-01 -4.7894e-01
  5.5329e-01  5.7174e-01  3.3249e-01  3.3135e-01  3.2713e-01 -1.2775e-01
 -7.5151e-02  1.4600e-01  1.1909e-01  1.2987e+00  1.4428e-01 -8.8560e-02
 -5.6583e-02 -2.0832e-01  3.7297e-02 -2.7068e-01  3.5929e-01  3.5666e-01
 -1.3602e-01 -2.6616e-01  5.1051e-02 -3.8901e-01 -7.1688e-01  4.2142e-01
  3.4138e-01  2.0226e-01  7.2525e-01 -8.2843e-02 -5.0313e-04  9.6399e-02
 -9.9015e-01 -2.5072e-01  1.3442e-01 -1.4179e-01  4.5943e-01  1.4141e-01
  2.2300e-01  2.5430e-01 -1.4116e-01  1.6485e-01  3.6200e-01  2.7605e-01
  4.2591e-01 -7.7762e-01 -3.0578e-01 -3.2377e-01 -1.4614e-01 -3.0976e-01
  2.0135e-02  8.5477e-01 -4.5221e-01  2.2912e-01 -1.6643e-02 -8.9288e-02
  5.5455e-01 -1.7363e-01  2.6326e-01  2.5399e-01 -6.9577e-01  1.2545e+00
  3.8360e-01  6.1884e-01 -1.9624e-01 -6.2276e-01  2.8007e-01 -3.0718e-01
 -4.5880e-01 -6.4558e-02  1.2010e-01 -3.7269e-01  2

In [9]:
import json
import re
with open("/content/drive/MyDrive/COMS574-Introduction_To_Machine_Learning/News_Category_Dataset_v3.json", "r",encoding='utf-8') as f:
    text = f.read()

#parse json in the files to extract text
pattern = '\{[^{}]*\}'

matches = re.findall(pattern, text)

In [ ]:
#size of dataset
len(matches)

209527

In [10]:
!pip install swifter
!pip install inflect
import inflect
from multiprocessing import Pool, cpu_count
#Also import all nltk libraries
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize, pos_tag, ne_chunk
from nltk.tree import Tree
nltk.download('punkt')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker_tab')
nltk.download('punkt_tab')

nltk.download('wordnet')
nltk.download('stopwords')
from nltk.corpus import words
#download and import dictionary of words
nltk.download('words')
word_list = words.words()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Packag

In [11]:
#create pandas dataframe out of json file
import pandas as pd
json_objs=[]
for item in matches:
  try:
     json_obj = json.loads(item)
     json_objs.append(json_obj)
  except json.JSONDecodeError:
     print(f"Could not decode: {item}")

df = pd.DataFrame(json_objs)


Could not decode: {Today's Buddha Doodle}
Could not decode: {Today's Buddha Doodle}
Could not decode: {This was originally posted to The Screaming", "date": "2013-08-08"}
Could not decode: {Newlywed}
Could not decode: {sic}
Could not decode: {EM}


In [ ]:
#The number of rows in dataframe
print(len(df))

209521


In [12]:
#category counts of ecah category
value_counts_column = df['category'].value_counts()
print(value_counts_column)

category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9899
STYLE & BEAUTY     9813
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3652
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1396
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1073
EDUCATI

In [59]:
#Just taking a subset of 15 categories which are relevant and have good amount of data
#Max 5000 rows are selected for eah category.
#This is to avoid bias towards particular category.
df_subset = pd.DataFrame()
categories_shortlisted =['POLITICS','WELLNESS','TRAVEL','STYLE & BEAUTY','SCIENCE','WOMEN','CRIME','BUSINESS','RELIGION'\
,'TECH','U.S. NEWS','WORLD NEWS','ENTERTAINMENT','HEALTHY LIVING','FOOD & DRINK']

for category in categories_shortlisted:
  temp_df = df[df['category'] == category]
  if len(temp_df) >=5000:
    temp_df = temp_df.sample(frac=5000/len(temp_df));
  df_subset = pd.concat([df_subset,temp_df],ignore_index=True)

print(len(df_subset))

58697


In [60]:
import copy
setwords = set(word_list)
p = inflect.engine()
#If its a dictionary word then just return the lowercase so its not identified as named entity.
#This is required for named entity recognition as the dictionary words should not be identified as named entities
def checkifItsDictionaryWord(token):
   word = copy.deepcopy(token)
   #Inorder to check if its a dictionary word, do some preprocessing
   #removal of 's or s' for any special characters.
   #also remove the inflections such as plural form.
   if "'s" in word:
     word.replace("'s","")
   elif "s'" in word:
     word.replace("s'","")

   res = p.singular_noun(word)
   #print(res)
   if res!=False:
      word = res

   word = re.sub(r'[^a-zA-Z0-9]', '', word)
   if word.lower() in setwords:
     del word;
     return token.lower()
   else:
     del word;
     return token



In [61]:
import inflect
import numpy as np

In [62]:
#Convert words to lower case if its a dictionary word so that its not falsely identified as named entity.
def convertWordsToLowerCase(sentence):
   tokens = [checkifItsDictionaryWord(token)  for token in sentence.split()]

   sentence = " ".join([token.lower() if token.lower() in setwords else token for token in tokens])
   return sentence

sentence = "Cars are best vehicles for Kate's travel"
print(convertWordsToLowerCase(sentence))

cars are best vehicles for Kate's travel


In [63]:
#Since all the words in headline are starting with CAPS we want to change it to lower case if its a dictionary word
#So that its not falsely identified as named entity
df_subset['headline'] = df_subset['headline'].apply(convertWordsToLowerCase)

In [64]:
#Finally concatenate the headline and short description.
df_subset['news_text'] = df_subset['headline']+ " "+df_subset['short_description']

In [65]:
def replaceChars(word):
  if "'s" in word:
     word.replace("'s","")
  elif "s'" in word:
     word.replace("s'","")
  return word;

def removeApostrophe(sent):
   tokens = sent.split()
   return " ".join([replaceChars(token) for token in tokens])

df_subset['news_text'] = df_subset['news_text'].apply(removeApostrophe)

In [66]:
import sys
#function to remove unicode characters
def remove_unicode(text):
    #print(text)
    return re.sub(r'[^\x00-\x7F]+', '', text)

#function to remove stopwords
def remove_stopwords(text):
    #text = "This is a simple sentence that contains some stop words."

    # Split the text into words
    words = text.split()

    # Get the list of stop words in English
    stop_words = set(stopwords.words('english'))

    # Remove stop words from the text
    filtered_words = [word for word in words if word.lower() not in stop_words]

    # Join the filtered words back into a sentence
    filtered_text = ' '.join(filtered_words)
    return filtered_text

#function to perform stemming and lemmatization.
def performLemmatizationAndStemming(text):
    words = text.split()

    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    lemmatized_words = []
    for word in words:
        try:
            lemmatized_words.append(lemmatizer.lemmatize(word,pos='v'))
        except:
            print('exception thrown')
            print(word)
            sys.exit()
    lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]  # Assuming verbs for simplicity

    # Stemming
    #stemmer = PorterStemmer()

    #stemmed_words = [stemmer.stem(word) for word in lemmatized_words]
    #stemmed_words = ' '.join(stemmed_words)
    lemmatized_words = ' '.join(lemmatized_words)
    return lemmatized_words


False

In [67]:
#not starting with A-Z or 0-9 delete it
df_subset['news_text'] = df_subset['news_text'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
#remove unicode
df_subset['news_text'] = df_subset['news_text'].apply(remove_unicode)
#df_subset['news_text'] = df_subset['news_text'].apply(remove_nondictionary_words)
#replace \n with ''
df_subset['news_text'] = df_subset['news_text'].str.replace(r'[\n]','',regex=True)

In [68]:
#remove stop words
df_subset['news_text'] = df_subset['news_text'].apply(remove_stopwords)

In [69]:
df_subset['news_text'] = df_subset['news_text'].apply(performLemmatizationAndStemming)

In [ ]:
df_subset['news_text'] = df_subset['news_text'].str.lower()

In [70]:
df_subset['news_text'].head()

0    backlash discrimination GOPs Indiana problem 2...
1    Chelsea man begin hunger strike need help get ...
2    dozens lawmakers urge Biden pick deb Haaland i...
3    heres NYC corrections could change Rikers isla...
4    save democracy prestige US Supreme Court issue...
Name: news_text, dtype: object

In [71]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.nn.utils.rnn import pad_sequence
from collections import Counter
import re


In [72]:
df_subset = df_subset.sample(frac=1).reset_index(drop=True)

In [73]:
sentence_list = df_subset['news_text'].tolist()

In [74]:
def pad_to_maxlen(sequences, maxlen, padding_value=0):
    padded = []
    for seq in sequences:
        if len(seq) < maxlen:
            # Pad at end
            pad_len = maxlen - len(seq)
            padded_seq = torch.cat([seq, torch.full((pad_len,), int(padding_value))])
            padded_seq = padded_seq.to(torch.int)
        else:
            # Truncate
            padded_seq = seq[:maxlen]
            padded_seq = padded_seq.to(torch.int)
        padded.append(padded_seq)
    return torch.stack(padded)

sequences = [torch.tensor([1, 2, 3]),
             torch.tensor([4, 5]),
             torch.tensor([6])]

padded = pad_to_maxlen(sequences, maxlen=4)
print(padded)


tensor([[1, 2, 3, 0],
        [4, 5, 0, 0],
        [6, 0, 0, 0]], dtype=torch.int32)


In [75]:
vocab = Counter(word for sentence in sentence_list for word in sentence)
vocab = {word: i+2 for i, (word, _) in enumerate(vocab.most_common())}
vocab['<PAD>'] = 0
vocab['<UNK>'] = 1
import sys
def encode(sentence):
    return [vocab.get(word, vocab['<UNK>']) for word in sentence]

maxlen = max([ len([word for word in sentence]) for sentence in sentence_list])
#print(maxlen)
#sys.exit()

encoded_sentences = [torch.tensor(encode(sentence)) for sentence in sentence_list]

# Padding
#padded_sentences = pad_sequence(encoded_sentences, batch_first=True, padding_value=vocab['<PAD>'],maxlen= 200)
padded_sentences = pad_to_maxlen(encoded_sentences,200,vocab['<PAD>'])
#print(padded_sentences[0])
#print(encoded_sentences[0])
print(padded_sentences[0])
#print([len([word for word in sent]) for sent in padded_sentences])
#sys.exit()

# Encode labels
labels = df_subset['category'].tolist()
one_hot = pd.get_dummies(df_subset['category'],dtype =float)
#rint(one_hot)
#sys.exit()
one_hot_tensor = one_hot.to_numpy()
print(one_hot_tensor)

tensor([28,  3, 10,  3, 11,  9, 16,  3,  2, 26,  6, 14, 41,  2, 12,  9, 24,  3,
         6,  2, 17,  4,  6, 16,  3,  6,  8,  2, 22,  4, 41,  4,  4,  6,  2, 15,
         4, 18,  2, 44, 34, 37, 44,  2,  6,  3, 24,  3,  4, 11,  2, 20,  4,  8,
        17,  7,  9, 10,  2,  9, 22,  8,  3,  8,  8,  7,  9, 10,  2, 28, 33, 31,
        29, 31, 25,  2, 25,  3,  3,  2, 28,  3, 10,  3, 11,  9, 16,  3,  8,  2,
         8,  5, 18, 11,  3,  2,  3, 24,  9, 11, 14,  5,  7,  9, 10,  2, 22,  6,
         3,  4,  5, 17,  3,  2,  8, 10,  4, 12, 23,  2,  4,  8,  7, 13,  3,  2,
        26,  6, 14, 41,  2, 16,  6,  3,  5,  5, 18,  2, 12,  9, 15, 20,  9,  6,
         5,  4, 22, 11,  3,  2, 17,  7, 19, 17,  2, 20,  4,  8, 17,  7,  9, 10,
         2,  5,  3, 11, 11,  2, 35,  4, 41,  4,  4,  6,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0], dtype=torch.int32)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0.

In [53]:
print(encoded_sentences[0])

tensor([29,  3, 10, 10,  3,  8,  8,  3,  3,  2,  4,  8,  8,  9, 12,  7,  4,  5,
         7,  9, 10,  2,  4, 15,  3, 10, 13,  2,  6, 14, 11,  3,  2, 33,  7, 47,
         4, 22, 43,  3,  4,  6,  7, 10, 19,  2,  8, 12, 17,  9,  9, 11,  2,  4,
         5, 17, 11,  3,  5,  3,  8,  2, 25,  5, 14, 13,  3, 10,  5,  8,  2, 21,
         3,  4,  6,  2, 17,  3,  4, 13,  8, 12,  4,  6, 24,  3,  8,  2, 11,  9,
        10, 19,  3,  6,  2,  6,  3, 51, 14,  7,  6,  3,  2,  8,  3,  3, 23,  2,
        21,  4,  7, 24,  3,  6,  2, 16,  4,  6,  5,  7, 12,  7, 16,  4,  5,  3,
         2,  8, 16,  9,  6,  5])


tensor([ 4,  1,  7,  ..., 12,  0,  1])


In [ ]:
len(embeddings_index['hello'])

200

In [76]:
embedding_dim = 200
embedding_matrix = torch.zeros(len(vocab), embedding_dim)

for word, idx in vocab.items():
    if word in embeddings_index:
        embedding_matrix[idx] = torch.from_numpy(embeddings_index[word]).float()

    else:
        embedding_matrix[idx] = torch.randn(embedding_dim)  # Random init for unknowns


tensor([[35,  9, 10,  ...,  0,  0,  0],
        [48,  3, 22,  ...,  0,  0,  0],
        [ 8,  9,  6,  ...,  0,  0,  0],
        ...,
        [ 6,  3, 13,  ...,  0,  0,  0],
        [26,  4, 11,  ...,  0,  0,  0],
        [21,  4,  8,  ...,  0,  0,  0]])


In [77]:
class SentenceDataset(Dataset):
    def __init__(self, inputs, labels):
        self.inputs = inputs
        self.labels = labels

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):
        return self.inputs[idx], self.labels[idx]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    padded_sentences, one_hot_tensor, test_size=0.3, random_state=42)



train_dataset = SentenceDataset(X_train, y_train)
test_dataset = SentenceDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)


In [90]:
class LSTMClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, output_dim):
        super(LSTMClassifier, self).__init__()
        self.embedding = nn.Embedding.from_pretrained(embedding_matrix, freeze=False);
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc1 = nn.Linear(hidden_dim, 25)

        self.fc2 = nn.Linear(25, output_dim)

    def forward(self, x):
        x = self.embedding(x)
        _, (hn, _) = self.lstm(x)
        fc1_out = self.fc1(hn[-1])
        fc1_relu = nn.ReLU()
        fc1_out = fc1_relu(fc1_out)
        fc2_out = self.fc2(fc1_out)
        return fc2_out;


In [91]:
import torch.nn.functional as F
from itertools import chain
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = LSTMClassifier(len(vocab), embed_dim=200, hidden_dim=256, output_dim=one_hot_tensor.shape[1]).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
for epoch in range(60):
    model.train()
    total_loss = 0
    num_batches = 0
    targets_entire_batch = []
    indices_entire_batch =[]
    accuracy_epoch =0
    total_size =0
    for inputs, targets in train_loader:
        #print(targets)
        #sys.exit()
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        probs = F.softmax(outputs, dim=1)
        #print(probs)
        #print(targets)
        #sys.exit()
        values, indices = torch.max(probs, dim=1)
        #print(indices.shape)
        #num_classes = indices.size()[0]
        #sys.exit()
        #predicted_one_hot = F.one_hot(indices, num_classes=15)
        target_normal = torch.argmax(targets,dim=1)
        #print(target_normal)
        #print(indices)
        correct = (indices == target_normal).sum().item()
        #accuracy = correct / targets.size(0)
        accuracy_epoch = accuracy_epoch+correct
        total_size = total_size+targets.size(0)
        #print(accuracy)
        #print(accuracy)
        #sys.exit()
        #targets_entire_batch.append(targets)
        #indices_entire_batch.append(predicted_one_hot)
        # Step 3: Compute accuracy


        #sys.exit()
        loss = criterion(outputs, targets)
        #print(loss)
        #sys.exit()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        num_batches += 1
    total_loss /= num_batches
    accuracy_epoch = accuracy_epoch/total_size;
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")
    print(f"Epoch {epoch+1}, Accuracy: {accuracy_epoch:.4f}")
    #sys.exit()

Epoch 1, Loss: 2.6237
Epoch 1, Accuracy: 0.1073
Epoch 2, Loss: 2.5820
Epoch 2, Accuracy: 0.1363
Epoch 3, Loss: 2.5487
Epoch 3, Accuracy: 0.1563
Epoch 4, Loss: 2.5072
Epoch 4, Accuracy: 0.1754
Epoch 5, Loss: 2.4079
Epoch 5, Accuracy: 0.2102
Epoch 6, Loss: 2.3532
Epoch 6, Accuracy: 0.2260
Epoch 7, Loss: 2.2937
Epoch 7, Accuracy: 0.2501
Epoch 8, Loss: 2.1431
Epoch 8, Accuracy: 0.2998
Epoch 9, Loss: 2.0236
Epoch 9, Accuracy: 0.3405
Epoch 10, Loss: 1.9257
Epoch 10, Accuracy: 0.3713
Epoch 11, Loss: 1.8237
Epoch 11, Accuracy: 0.4025
Epoch 12, Loss: 1.7265
Epoch 12, Accuracy: 0.4393
Epoch 13, Loss: 1.6249
Epoch 13, Accuracy: 0.4731
Epoch 14, Loss: 1.5266
Epoch 14, Accuracy: 0.5071
Epoch 15, Loss: 1.4344
Epoch 15, Accuracy: 0.5388
Epoch 16, Loss: 1.3493
Epoch 16, Accuracy: 0.5649
Epoch 17, Loss: 1.2723
Epoch 17, Accuracy: 0.5896
Epoch 18, Loss: 1.2015
Epoch 18, Accuracy: 0.6122
Epoch 19, Loss: 1.1303
Epoch 19, Accuracy: 0.6351
Epoch 20, Loss: 1.0655
Epoch 20, Accuracy: 0.6551
Epoch 21, Loss: 1.

In [92]:
def evaluate(model, test_loader, criterion):
    model.eval()  # set to evaluation mode
    total_loss = 0.0
    predictions = []
    actuals = []
    accuracy = 0
    with torch.no_grad():  # no gradient needed during inference
        for batch_X, batch_y in test_loader:
            batch_X, batch_y = batch_X.to(device), batch_y.to(device)
            output = model(batch_X).squeeze()
            loss = criterion(output, batch_y)
            probs = F.softmax(outputs, dim=1)
            values, indices = torch.max(probs, dim=1)
            target_normal = torch.argmax(targets,dim=1)
            correct = (indices == target_normal).sum().item()
            accuracy = accuracy+correct
            total_loss += loss.item() * batch_X.size(0)  # accumulate loss
            predictions.append(output)
            actuals.append(batch_y)

    avg_loss = total_loss / len(test_loader.dataset)
    predictions = torch.cat(predictions)
    actuals = torch.cat(actuals)
    print("The accuracy is")
    print(accuracy/len(test_loader.dataset))
    #return avg_loss, predictions, actuals
evaluate(model, test_loader, criterion)

The accuracy is
0.7509369676320272


In [ ]:
from functools import reduce
def getEmbeddingsNews(sent):
  tokens = sent.split()
  #print(tokens)
  vector_sum = np.zeros(100)
  vector_temp = np.zeros(embeddings_size)
  mapped_data = map(lambda x: (x, 1), tokens)
  result = reduce(lambda acc, x: (acc[0] + embeddings_index[x[0]], acc[1]+x[1]) if x[0] in embeddings_index else acc, mapped_data, (0,0))
  #print(result[1])
  if result[1] == 0:
    print(tokens)
    print(sent)
    return vector_temp
  return result[0]/result[1]

In [ ]:
df_subset['news_text_embeddings'] = df_subset['news_text'].apply(getEmbeddingsNews)

[]

['ahhhhhh']
ahhhhhh
[]

['intomesee']
intomesee
[]

['ladyinwaiting']
ladyinwaiting
['metabolenvy']
metabolenvy
['romantical']
romantical
[]



0    [-0.13869067, 0.34021485, 0.40968797, 0.031654...
1    [0.12643987, 0.17112476, 0.494685, -0.14378382...
2    [-0.07266141, 0.36068875, 0.34253892, -0.03346...
3    [-0.16239074, 0.3124193, 0.2653063, -0.2430215...
4    [-0.19659296, -0.1122778, 0.39440867, 0.031872...
Name: news_text_embeddings, dtype: object

In [ ]:
df_subset['news_text_embeddings'].head()

0    [0.14322297, 0.29859707, 0.07154488, -0.049467...
1    [-0.31627104, 0.106928304, -0.2191517, -0.2303...
2    [-0.10568069, 0.30309823, -0.0054959967, -0.03...
3    [0.027149007, 0.05887452, -0.10680344, 0.05987...
4    [-0.022456072, 0.14850293, -0.22473784, 0.0530...
Name: news_text_embeddings, dtype: object

In [ ]:
df_subset = df_subset.sample(frac =1.0, random_state=42);

In [ ]:

categories = set(df_subset['category'].unique())
categories_list = list(categories)
categories_index = [categories_list.index(category) for category in df_subset['category']]

In [ ]:
array_df_subset = df_subset['news_text_embeddings'].values
list_df_subset = list(array_df_subset)

In [ ]:
df_subset['news_text_embeddings'][0]

array([-1.38690665e-01,  3.40214849e-01,  4.09687966e-01,  3.16547640e-02,
       -1.16282105e-01, -9.95175242e-02, -1.21507749e-01, -2.41518617e-02,
       -5.44838086e-02, -1.45383179e-03, -5.91842867e-02, -1.49804562e-01,
        2.47853324e-02, -1.37979567e-01, -8.77080392e-03, -2.63854712e-01,
        3.58655825e-02,  5.54210171e-02, -2.97050625e-01,  1.37238884e-02,
        2.08153620e-01,  8.45340937e-02,  9.29854140e-02,  8.45331177e-02,
       -1.53387576e-01, -9.32770818e-02,  3.15355286e-02, -5.28422058e-01,
        5.96001074e-02, -9.00440961e-02,  3.70324701e-02,  3.50540012e-01,
        4.65538760e-04, -4.44586128e-02,  6.80771694e-02,  2.37027466e-01,
        7.10499734e-02,  1.61411166e-01, -1.72917247e-01,  1.00211568e-01,
       -5.22332370e-01, -2.56896585e-01,  3.04283034e-02, -2.31903449e-01,
       -2.25978315e-01, -9.90635604e-02,  1.34553552e-01,  7.54389688e-02,
       -3.98006886e-01, -6.61410570e-01,  1.99954603e-02, -2.32198402e-01,
       -6.10017926e-02,  

In [ ]:
from sklearn.decomposition import PCA
pca_model = PCA(n_components=0.90)
list_df_subset_reduced = pca_model.fit_transform(list_df_subset)

In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(list_df_subset_reduced, categories_index, test_size=0.2, random_state=100)

# Define the kernels to be used
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
kernel_chosen = kernels[2]
clf = SVC(kernel=kernel_chosen,C=1.7)

# Train the classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

y_pred = clf.predict(X_train)

# Calculate the accuracy of the classifier
#accuracy = accuracy_score(y_test, y_pred)
accuracy = accuracy_score(y_train, y_pred)

# Print the results
print(f"Accuracy with {kernel_chosen} kernel: {accuracy:.2f}")

Accuracy with rbf kernel: 0.84


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(list_df_subset, categories_index, test_size=0.2, random_state=42)

# Create and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.63


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
